# Site settings
title: Anna's Chunky Bacon and Sweater House
email: shinshinwu <at> gmail.com
description: Programming and all other random thoughts
baseurl: /myblog/ # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: cakeisnotreal
github_username:  shinshinwu

# Build settings
markdown: kramdown
